# Generated by Django 2.0.2 on 2018-02-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_main_story', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='passage',
            name='is_ending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='from_passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='story.Passage'),
        ),
        migrations.AddField(
            model_name='choice',
            name='to_passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='story.Passage'),
        ),
        migrations.AddField(
            model_name='passage',
            name='pov_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='story.Character'),
        ),
        migrations.AddField(
            model_name='passage',
            name='to_passages',
            field=models.ManyToManyField(null=True, through='story.Choice', to='story.Passage'),
        ),
    ]
