# Generated by Django 2.0.2 on 2018-02-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20180211_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='to_passages',
            field=models.ManyToManyField(through='story.Choice', to='story.Passage'),
        ),
    ]
