# Generated by Django 2.0.2 on 2018-02-11 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20180211_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='passage',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='story.Story'),
            preserve_default=False,
        ),
    ]
