# Generated by Django 2.0.2 on 2018-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_story_published_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='number',
        ),
        migrations.AddField(
            model_name='passage',
            name='name',
            field=models.CharField(default='something', max_length=50),
            preserve_default=False,
        ),
    ]
