# Generated by Django 2.2 on 2019-04-08 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_remove_story_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='published_year',
        ),
        migrations.AddField(
            model_name='story',
            name='published_date',
            field=models.DateField(default=datetime.date(2019, 4, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='story.Author'),
        ),
    ]
