# Generated by Django 2.2 on 2019-04-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_auto_20190408_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='twitter_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
