# Generated by Django 2.2 on 2019-04-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_auto_20190416_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
